# Generated by Django 5.2.7 on 2025-10-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=100)),
                ('blog_info', models.CharField(max_length=500)),
                ('blog_detail', models.CharField()),
                ('blog_pic', models.ImageField(default='default.img', upload_to='blog_images/')),
            ],
        ),
    ]
